# configs de PROD
gateway:
  replicaCount: 2
  # duas cópias do kong rodando(margem de segurança, caso uma caia)

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  # configs de infra do gateway para PROD

  proxy:
    type: LoadBalancer
    # sobrescrita do valor padrão (ClusterIP)
    # pede pro EKS Auto Mode criar uma Network Load Balancer acessível pela internet

    loadBalancerClass: "eks.amazonaws.com/nlb"
    # cluster em EKS AUTO MODE -> AWS Network Load Balancer(NLB) implementação usada

    annotations:
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      # nlb direto para o IP dos pods em vez do node

      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      # torna a NLB acessível pela internet, em vez de apenas internal

      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true"
      # liga a preservação de ip do client -> ip é a referencia do rate-limiting

# sem ip fixo no modo EKS Auto Mode